#!/usr/bin/env/python3

print("welcome to the band name generator")
city = input("what's the name of the city you grew up in?\n")
pet = input("what's the name of your pet\n")
print("your band name is " + city + " " + pet)
